Models/ManagerViewModel.cs
using MatchTechWebsite.Models;
using MatchTechWebsite.sakila;
using MatchTechWebsite.ViewComponents;

namespace MatchTechWebsite.Models
{
    public class ManagerViewModel
    {
        //public List<Matchdayfixture>? Matchdayfixtures { get; set; }

        public List<sakila.Tournament>? Tournaments { get; set; }
    }


    public class ManagerCreateViewModel
    {
        public List<string> TournamentSelector = new List<string>() { "Round Robin", "Knockout" };
        public List<sakila.Team> TeamSelector { get; set; }

        public string TournamentName { get; set; }
        public string TournamentType { get; set; }
        public List<int> Teams { get; set; }
        public DateTime StartDate { get; set; }
        public List<DateTime> HolidayDates { get; set; }
        public List<DateTime> SpecialRequests { get; set; }
        public List<string> MatchDays { get; set; }
        public int Rounds { get; set; }

    }


    public class ManagerEditViewModel
    {
        public sakila.Tournament? tournament { get; set; }

        //public List<MatchweekMatchday>? MatchweekMatchdays { get; set; }
        public List<MatchWeek>? MatchWeeks { get; set; }

        //public Matchdayfixture Matchdayfixture { get; set; }

        //public MatchTile MatchTile { get; set; }
    }


    public class ManagerDeleteViewModel
    {
        public sakila.Tournament? tournament { get; set; }

    }


}

Components/MatchTileViewComponent.cs
using MatchTechWebsite.Models;
using MatchTechWebsite.sakila;
using Microsoft.AspNetCore.Mvc;

namespace MatchTechWebsite.ViewComponents
{
    public class MatchTileViewComponent : ViewComponent
    {
        MatchDay myMatch;

        public MatchTileViewComponent()
        {
            
        }



        public async Task<IViewComponentResult> InvokeAsync(MatchDay match)
        {
            myMatch = match;
            return await Task.FromResult((IViewComponentResult)View("MatchTile", myMatch));
        }


    }
}

Controllers/ManagerController.cs
using MatchTechWebsite.Models;
using MatchTechWebsite.sakila;
using MatchTechWebsite.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using System;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Linq.Expressions;
using System.Net.Http.Headers;

namespace MatchTechWebsite.Controllers
{
    public class ApiParam {
        public string TournamentName { get; set; }
        public string TournamentType { get; set; }
        public List<int> Teams { get; set; }
        public DateTime StartDate { get; set; }
        public int Rounds { get; set; }
    }

    public class ManagerController : Controller
    {
        DbAa1c85MtechContext _context = new DbAa1c85MtechContext();
        public IActionResult Index()
        {
            var viewModel = new ManagerViewModel
            {
                Tournaments = _context.Tournaments.ToList()
            };
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {


            var viewModel = new ManagerCreateViewModel
            {
                TeamSelector = _context.Teams.ToList()

            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(string TournamentName, string TournamentType, List<int> Teams, DateTime StartDate, int Rounds)
        {
            Console.WriteLine(TournamentName);
            Console.WriteLine(TournamentType);
            Console.WriteLine(Teams.Count());
            foreach (var team in Teams)
            {
                Console.WriteLine(team);
            }
            Console.WriteLine(StartDate);
            Console.WriteLine(Rounds);

            string EmpInfo  = "none";
            string Baseurl = "http://localhost:5000/";
            using (var client = new HttpClient())
            {
                //Passing service base url
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                //Define request data format
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                //Sending request to find web api REST service resource GetAllEmployees using HttpClient
                var jsonParam = new ApiParam { TournamentName = TournamentName, TournamentType = TournamentType, Teams = Teams, StartDate = StartDate, Rounds = Rounds };

                HttpResponseMessage Res = await client.PostAsJsonAsync("api/TournamentController", jsonParam);
                //Checking the response is successful or not which is sent using HttpClient
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    Console.WriteLine(EmpResponse);

                    //Deserializing the response recieved from web api and storing into the Employee list
                    //EmpInfo = JsonConvert.DeserializeObject<string>(EmpResponse);
                }

                //Console.WriteLine(EmpInfo);
                //returning the employee list to view
                //return View();
            }




            var viewModel = new ManagerViewModel
            {
                Tournaments = _context.Tournaments.ToList()
            };
            return View(nameof(Index), viewModel);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            sakila.Tournament t = _context.Tournaments.Where(t => t.Id == id).FirstOrDefault();
            List<MatchweekMatchday> matchweek_matchdays = _context.MatchweekMatchdays.Where(m => m.MatchWeekKeyNavigation.TournamentKey == id).ToList();
            List<MatchWeek> matchweeks = new List<MatchWeek> ();
            MatchWeek matchWeek;
            MatchDay matchDay;
            int? matchWeekIndex;
            foreach (var item in matchweek_matchdays)
            {
                matchWeek = new MatchWeek(item.MatchWeekKey, item.MatchWeekKeyNavigation.Week);
                matchDay = new MatchDay(item.MatchDayKeyNavigation);
                
                matchWeekIndex = WeekExistsAtIndex(matchweeks, matchWeek.Week);
                if (matchWeekIndex == null)
                {
                    matchweeks.Add(matchWeek);
                    matchweeks[^1].Add(matchDay);
                }
                else {
                    matchweeks[(int)matchWeekIndex].Add(matchDay);
                }
            
            }

            var viewModel = new ManagerEditViewModel
            {
                tournament = t,
                MatchWeeks = matchweeks
            };

            return View(viewModel);
        }



        [HttpPost]
        public JsonResult Edit(string action, int id, DateTime datetime, int weekId=0, int fieldId=0)
        {
            Console.WriteLine(action);
            Console.WriteLine(id);
            Console.WriteLine(datetime);
            Console.WriteLine(weekId);
            JsonResult jsonReponse;
            switch (action)
            {
                case "ChangeDate":
                    // code block
                    jsonReponse = ChangeDate(id, datetime, fieldId);
                    break;
                case "MoveTile":
                    // code block
                    jsonReponse = MoveTile(id, datetime, weekId);
                    break;
                default:
                    // code block
                    jsonReponse = Json(new { weekId = weekId });
                    break;
            }

            return jsonReponse;
        }


        public JsonResult MoveTile(int id, DateTime datetime, int weekId)
        {
            Console.WriteLine(id);
            Console.WriteLine(datetime);
            Console.WriteLine(weekId);
            var matchWeekMatchDay = _context.MatchweekMatchdays.Where(m => m.MatchDayKey == id).FirstOrDefault();
            var newWeek = _context.Matchweekfixtures.Where(w => w.Id == weekId).FirstOrDefault().Week;
            int currWeek = matchWeekMatchDay.MatchWeekKeyNavigation.Week;

            int dateTimeOffset = newWeek - currWeek;

            var newDateTime = datetime.AddDays(dateTimeOffset * 7);
            matchWeekMatchDay.MatchWeekKey = weekId;
            matchWeekMatchDay.MatchDayKeyNavigation.DateTime = newDateTime;

            _context.SaveChanges();
            return Json(new { weekId = weekId, dateTime = newDateTime });
        }


        public JsonResult ChangeDate(int id, DateTime datetime, int fieldId)
        {
            Console.WriteLine(id);
            Console.WriteLine(datetime);
            Console.WriteLine(fieldId);
            var matchdayfixture = _context.Matchdayfixtures.Where(m => m.Id == id).FirstOrDefault();
            matchdayfixture.DateTime = datetime;
            matchdayfixture.FieldKey = fieldId;

            _context.SaveChanges();
            return Json(new { dateTime = datetime, fieldId = fieldId });
        }


        [HttpGet]
        public JsonResult AvailableFields(int id)
        {
            var matchday = _context.Matchdayfixtures.Find(id);
            var matchdayfixtures = _context.Matchdayfixtures.Where(m => m.DateTime.Date == matchday.DateTime.Date).ToList();
            var allFields = _context.Fields.ToList();
            var usedFields = (from m in matchdayfixtures
                              join f in _context.Fields
                              on m.FieldKey equals f.Id
                              select f).ToList();

            var availableFields = allFields
                   .Where(x => !usedFields.Any(y => y.Id == x.Id));

            Console.WriteLine("AvailableFields");

            foreach (var f in availableFields)
            {
                Console.WriteLine(f.Name);
            }

            return Json(new { fields = availableFields });
        }



        [HttpGet]
        public IActionResult Delete(int? id)
        {

            var tournament = _context.Tournaments.Where(t => t.Id == id).FirstOrDefault();
            return View(tournament);
        }



        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var matchweekfixtures = _context.Matchweekfixtures.Where(m => m.TournamentKey == id);

            var query = from m in matchweekfixtures
                        join w in _context.MatchweekMatchdays
                        on m.Id equals w.MatchWeekKey
                        select w;

            var matchdayfixtures = from p in query
                                   select p.MatchDayKeyNavigation;

            _context.Matchweekfixtures.RemoveRange(matchweekfixtures);
            _context.Matchdayfixtures.RemoveRange(matchdayfixtures);


            //foreach (var matchweek in matchweekfixtures)
            //{
            //    var m = _context.MatchweekMatchdays.Where(m => m.MatchWeekKey == matchweek.Id).FirstOrDefault();
            //    if (m != null) {
            //        _context.Remove(m);
            //    }

            //}

            var t = _context.Tournaments.Where(t => t.Id == id).FirstOrDefault();
            _context.Remove(t);

            _context.SaveChanges();

            var viewModel = new ManagerViewModel
            {
                Tournaments = _context.Tournaments.ToList()
            };
            return View(nameof(Index), viewModel);
        }


        public IActionResult MatchTileComponent(Matchdayfixture match)
        {
            return ViewComponent("MatchTile", new { match });
        }









        [HttpPost]
        public JsonResult ChangeWeek(int id, int week=4)
        {
            Console.WriteLine("ChangeWeek");
            Console.WriteLine(id);

Views/Manager/Create.cshtml
@model MatchTechWebsite.Models.ManagerCreateViewModel;


<script src="~/js/script.js" defer></script>

<form asp-controller="Manager" asp-action="Create">
    <div class="form-group SCF">
        <input placeholder="Tournament Name" asp-for="TournamentName" type="text" />
        <span asp-validation-for="TournamentName" class="text-danger"></span>
    </div>
    <div class="form-group SCF">
        <select asp-for="TournamentType">
            @foreach (var item in Model.TournamentSelector)
            {
                <option value="@item">@item</option>
            }
        </select>
        <span asp-validation-for="TournamentType" class="text-danger"></span>
    </div>
    <div class="form-group SCF">
        <select class="chosen-select" multiple="true" asp-for="Teams" style="width:200px;">
            @foreach (var item in Model.TeamSelector)
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
        <span asp-validation-for="Teams" class="text-danger"></span>
    </div>
    <div class="form-group SCF">
        <label asp-for="StartDate" class="control-label"></label>
        <input asp-for="StartDate" asp-format="{0:yyyy-MM-dd}" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>
    <div class="form-group SCF">
        <input asp-for="Rounds" placeholder="Rounds" min="1" />
        <span asp-validation-for="Rounds" class="text-danger"></span>
    </div>

    <input type="submit" value="Create" class="btn btn-primary" />
</form>

Views/Manager/Delete.cshtml
@model MatchTechWebsite.sakila.Tournament;

@{
    ViewData["Title"] = "Delete";
    // Layout = "_Layout";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Manager/Edit.cshtml
@model MatchTechWebsite.Models.ManagerEditViewModel;

<script src="~/js/script.js" defer></script>

<div class="match-tournament">
    @foreach (var matchWeek in Model.MatchWeeks)
    {
        <div class="match-container" weekId="@matchWeek.Id">
            <span>Week @matchWeek.Week</span>
            @foreach (var match in matchWeek.MatchDays)
            {
                @await Component.InvokeAsync("MatchTile", new { match = match });
            }
        </div>
    }
</div>

Views/Manager/Index.cshtml
@model MatchTechWebsite.Models.ManagerViewModel;



<h1>Manager</h1>

<a class="tournament-create btn" asp-action="Create">Create</a>


@foreach (var item in Model.Tournaments)
{
    <p>@Html.DisplayFor(modelItem => item.Name)</p> 
    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
}